# Generated by Django 4.1.2 on 2022-10-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chart1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="turbit",
            old_name="rotor",
            new_name="power",
        ),
    ]
